"""Initial migration with password reset

Revision ID: 61adb55380c9
Revises: 
Create Date: 2025-03-13 00:25:11.091843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61adb55380c9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('security_question', sa.String(length=250), nullable=False))
        batch_op.add_column(sa.Column('security_answer', sa.String(length=250), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('security_answer')
        batch_op.drop_column('security_question')

    # ### end Alembic commands ###
